[package]
name = "easyparquet"
version = "0.1.0"
edition = "2024"

[dependencies]
arrow = "55.1.0"
dotenvy = "0.15.7"
futures = "0.3.31"
mysql_async = "0.36.1"
parquet = { version = "55.2.0", features = ["arrow"] }
tokio = { version = "1.45.1", features = ["full"] }
